### ISSUE TITLE
translation files

### ISSUE THREAD

**Issue by cbrake** [g-timetracker/g-timetracker#1]
Hi, getting:

RCC: Error in '../../../g-timetracker/src/app/translations.qrc': Cannot find file 'translations/timetracker_en.qm'

What is the best way to generate the translation files?

I'm using qt 5.7 on arch linux.

**Comment by krnekit** [comment]
Hi!
To generate translations, use:
`$ lrelease src/src.pro`

**Comment by cbrake** [comment]
thanks, that worked -- looks great!
